# Used for benchmarking
FROM rebenchdb-app:latest

RUN apt-get update && apt-get install -y git python3-pip
RUN pip install --break-system-packages git+https://github.com/smarr/ReBench.git

RUN npm run pretest

ENTRYPOINT ["rebench"]
CMD ["--help"]
