-- Add NOT NULL constraints to the Run table
ALTER TABLE Run ALTER COLUMN benchmarkId SET NOT NULL;
ALTER TABLE Run ALTER COLUMN suiteId SET NOT NULL;
ALTER TABLE Run ALTER COLUMN execId SET NOT NULL;
ALTER TABLE Run ALTER COLUMN cmdline SET NOT NULL;
ALTER TABLE Run ALTER COLUMN maxInvocationTime SET NOT NULL;
ALTER TABLE Run ALTER COLUMN minIterationTime SET NOT NULL;
